sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker version

  - docker build --no-cache -t jorge07/alpine-php:7.4 -f 7.4/Dockerfile 7.4/
  - docker build --no-cache -t jorge07/alpine-php:7.4-dev -f 7.4/Dockerfile.dev 7.4/
  - docker build --no-cache -t jorge07/alpine-php:7.4-front -f 7.4/Dockerfile.front 7.4/

  - docker build --no-cache -t jorge07/alpine-php:7.3 -f 7.3/Dockerfile 7.3/
  - docker build --no-cache -t jorge07/alpine-php:7.3-dev -f 7.3/Dockerfile.dev 7.3/
  - docker build --no-cache -t jorge07/alpine-php:7.3-front -f 7.3/Dockerfile.front 7.3/

  - docker build --no-cache -t jorge07/alpine-php:7.2 -f 7.2/Dockerfile 7.2/
  - docker build --no-cache -t jorge07/alpine-php:7.2-dev -f 7.2/Dockerfile.dev 7.2/
  - docker build --no-cache -t jorge07/alpine-php:7.2-front -f 7.2/Dockerfile.front 7.2/

  - docker build --no-cache -t jorge07/alpine-php:7.1 -f 7.1/Dockerfile 7.1/
  - docker build --no-cache -t jorge07/alpine-php:7.1-dev -f 7.1/Dockerfile.dev 7.1/
  - docker build --no-cache -t jorge07/alpine-php:7.1-front -f 7.1/Dockerfile.front 7.1/

  - docker build --no-cache -t jorge07/alpine-php:5.6 -f 5.6/Dockerfile 5.6/
  - docker build --no-cache -t jorge07/alpine-php:5.6-dev -f 5.6/Dockerfile.dev 5.6/

  - docker run --name php7.4 -d -v $PWD:/app jorge07/alpine-php:7.4
  - docker run --name php7.4-dev -d -v $PWD:/app jorge07/alpine-php:7.4-dev
  - docker run --name php7.4-front -d -v $PWD:/app jorge07/alpine-php:7.4-front

  - docker run --name php7.3 -d -v $PWD:/app jorge07/alpine-php:7.3
  - docker run --name php7.3-dev -d -v $PWD:/app jorge07/alpine-php:7.3-dev
  - docker run --name php7.3-front -d -v $PWD:/app jorge07/alpine-php:7.3-front

  - docker run --name php7.2 -d -v $PWD:/app jorge07/alpine-php:7.2
  - docker run --name php7.2-dev -d -v $PWD:/app jorge07/alpine-php:7.2-dev
  - docker run --name php7.2-front -d -v $PWD:/app jorge07/alpine-php:7.2-front

  - docker run --name php7.1 -d -v $PWD:/app jorge07/alpine-php:7.1
  - docker run --name php7.1-dev -d -v $PWD:/app jorge07/alpine-php:7.1-dev
  - docker run --name php7.1-front -d -v $PWD:/app jorge07/alpine-php:7.1-front

  - docker run --name php5 -d -v $PWD:/app jorge07/alpine-php:5.6
  - docker run --name php5-dev -d -v $PWD:/app jorge07/alpine-php:5.6-dev

  - docker-compose -f test/docker-compose.yml up -d

script:
  - docker exec php7.4 php -v
  - docker exec php7.4 sh -c "php -v | grep 7.4"
  - docker exec php7.4 sh -c "php -v | grep OPcache"
  - docker exec php7.4 sh -c "php test/test.php | grep Iyo"
  - docker exec php7.4 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 256M"

  - docker exec php7.3 php -v
  - docker exec php7.3 sh -c "php -v | grep 7.3"
  - docker exec php7.3 sh -c "php -v | grep OPcache"
  - docker exec php7.3 sh -c "php test/test.php | grep Iyo"
  - docker exec php7.3 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 256M"

  - docker exec php7.2 php -v
  - docker exec php7.2 sh -c "php -v | grep 7.2"
  - docker exec php7.2 sh -c "php -v | grep OPcache"
  - docker exec php7.2 sh -c "php test/test.php | grep Iyo"
  - docker exec php7.2 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 256M"

  - docker exec php7.2-dev sh -c "php -v | grep Xdebug"
  - docker exec php7.2-dev composer --version
  - docker exec php7.2-dev sh -c "php test/test.php | grep Iyo"
  - docker exec php7.2-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 1G"

  - docker exec php7.4-dev sh -c "php -v | grep Xdebug"
  - docker exec php7.4-dev composer --version
  - docker exec php7.4-dev sh -c "php test/test.php | grep Iyo"
  - docker exec php7.4-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 1G"

  - docker exec php7.3-dev sh -c "php -v | grep Xdebug"
  - docker exec php7.3-dev composer --version
  - docker exec php7.3-dev sh -c "php test/test.php | grep Iyo"
  - docker exec php7.3-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 1G"

  - docker exec php7.1 php -v
  - docker exec php7.1 sh -c "php -v | grep 7.1"
  - docker exec php7.1 sh -c "php -v | grep OPcache"
  - docker exec php7.1 sh -c "php test/test.php | grep Iyo"
  - docker exec php7.1 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 256M"

  - docker exec php7.1-dev sh -c "php -v | grep Xdebug"
  - docker exec php7.1-dev composer --version
  - docker exec php7.1-dev sh -c "php test/test.php | grep Iyo"
  - docker exec php7.1-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 1G"

  - docker exec php7.1-front node -v
  - docker exec php7.1-front yarn --version

  - docker exec php5 php -v
  - docker exec php5 sh -c "php -v | grep OPcache"
  - docker exec php5 sh -c "php test/test.php | grep Iyo"
  - docker exec php5 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 256M"

  - docker exec php5-dev php -v | grep Xdebug
  - docker exec php5-dev composer --version
  - docker exec php5-dev sh -c "php test/test.php | grep Iyo"
  - docker exec php5-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 2G"

  - docker exec test_fpm_1 sh -c "curl nginx | grep Iyo"
